server:
  port: 9090
spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: 121.43.234.130:8848
      config:
        server-addr: 121.43.234.130:8848
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true #gateway 可以从nacos发现服务，过gateway调用其他的微服务
      routes:
        - id: user-service # 自己命名的，只要唯一即可
          uri: lb://user-service #强对应user-service的spring.application.name
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1 #使用过滤器
